{% set name = "awkward" %}
{% set version = "2.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-{{ version }}.tar.gz
  sha256: d7f8a600aa1031df87b2c9bd2fc5c41fb78dac514e1feb37f8b5034f358aaf97

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >1.10.0
    - hatch-fancy-pypi-readme
  run:
    - python >=3.7
    - awkward-cpp ==14
    - importlib_resources
    - numpy >=1.17.0
    - packaging
    - typing_extensions

test:
  imports:
    - awkward
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/awkward-1.0
  summary: Manipulate JSON-like data with NumPy-like idioms.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
    - henryiii
    - agoose77
    - conda-forge/scikit-hep
    - ioanaif
